-------------------------------- This data was generated by Gemini --------------------------------

EXEC Add_Branch '100-200-300', 'Mansoura';			-- ID: 1
EXEC Add_Branch '400-500-600', 'Cairo';				-- ID: 2
EXEC Add_Branch '700-800-900', 'Alex';				-- ID: 3

EXEC Add_Safe 1, 'Main', 100000;			-- ID: 1
EXEC Add_Safe 1, 'Till', 5000;				-- ID: 2
EXEC Add_Safe 2, 'Main', 100000;			-- ID: 3
EXEC Add_Safe 2, 'Till', 5000;				-- ID: 4
EXEC Add_Safe 3, 'Main', 100000;			-- ID: 5
EXEC Add_Safe 3, 'Till', 5000;				-- ID: 6


-- (Mansoura)
EXEC Add_Employee 'Dr. Khaled', 'Manager', '0101555001', 1, 'Morning';			-- ID: 1
EXEC Add_Employee 'Samy', 'Cashier', '0101555002', 1, 'Morning';				-- ID: 2
EXEC Add_Employee 'Hany', 'Cashier', '0101555006', 1, 'Evening';				-- ID: 3
EXEC Add_Employee 'Ziad', 'Cashier', '0101555010', 1, 'Night';					-- ID: 4
EXEC Add_Employee 'Ali', 'Delivery', '0101555003', 1, 'Morning';				-- ID: 5
EXEC Add_Employee 'Mohamed', 'Delivery', '0101555007', 1, 'Evening'				-- ID: 6
EXEC Add_Employee 'Sayed', 'Delivery', '0101555011', 1, 'Night';				-- ID: 7
EXEC Add_Employee 'Dr. Ahmed', 'Pharmacist', '0101555004', 1, 'Morning';		-- ID: 8
EXEC Add_Employee 'Dr. Sara', 'Pharmacist', '0101555005', 1, 'Morning';			-- ID: 9
EXEC Add_Employee 'Dr. Mona', 'Pharmacist', '0101555008', 1, 'Evening';			-- ID: 10
EXEC Add_Employee 'Dr. Omar', 'Pharmacist', '0101555009', 1, 'Evening';			-- ID: 11
EXEC Add_Employee 'Dr. Zaki', 'Pharmacist', '0101555012', 1, 'Night';			-- ID: 12
EXEC Add_Employee 'Dr. Nour', 'Pharmacist', '0101555013', 1, 'Night';			-- ID: 13

----------------

EXEC Add_Manufacturer 'Pfizer', 'USA', '001-PFZ';
EXEC Add_Manufacturer 'GlaxoSmithKline', 'UK', '0044-GSK';
EXEC Add_Manufacturer 'Novartis', 'Switzerland', '0041-NOV';
EXEC Add_Manufacturer 'Sanofi', 'France', '0033-SAN';
EXEC Add_Manufacturer 'Eva Pharma', 'Egypt', '02-EVA';
EXEC Add_Manufacturer 'AstraZeneca', 'UK/Sweden', '0044-AZ';
EXEC Add_Manufacturer 'Bayer', 'Germany', '0049-BAY';
EXEC Add_Manufacturer 'Merck', 'Germany', '0049-MRK';
EXEC Add_Manufacturer 'Amoun', 'Egypt', '02-AMN';

EXEC Add_Category 'Antibiotics';	   -- ID: 1
EXEC Add_Category 'Analgesics';        -- ID: 2
EXEC Add_Category 'Diabetes';          -- ID: 3
EXEC Add_Category 'Cardiovascular';    -- ID: 4
EXEC Add_Category 'Gastrointestinal';  -- ID: 5

EXEC Add_Sub_Category 'Oral Antibiotics', 1;      -- ID: 1
EXEC Add_Sub_Category 'Pain Relief', 2;           -- ID: 2
EXEC Add_Sub_Category 'Oral Hypoglycemics', 3;    -- ID: 3
EXEC Add_Sub_Category 'Hypertension Drugs', 4;    -- ID: 4
EXEC Add_Sub_Category 'Antacids', 5;              -- ID: 5

EXEC Add_Active_Ing 'Amoxicillin';         -- ID: 1
EXEC Add_Active_Ing 'Clavulanic Acid';     -- ID: 2
EXEC Add_Active_Ing 'Paracetamol';         -- ID: 3
EXEC Add_Active_Ing 'Caffeine';            -- ID: 4
EXEC Add_Active_Ing 'Vildagliptin';        -- ID: 5
EXEC Add_Active_Ing 'Metformin';           -- ID: 6
EXEC Add_Active_Ing 'Amlodipine';          -- ID: 7
EXEC Add_Active_Ing 'Valsartan';           -- ID: 8
EXEC Add_Active_Ing 'Omeprazole';          -- ID: 9

EXEC Add_Dosage_Form 'Tablets';
EXEC Add_Dosage_Form 'Syrup';
EXEC Add_Dosage_Form 'Capsules';
EXEC Add_Dosage_Form 'Injection';


DECLARE @ing_aug Ingredients_List; 
INSERT INTO @ing_aug VALUES (1), (2);
EXEC Add_Product 'Augmentin 1g', 'BAR-001', 2, 1, 1, @ing_aug;

DECLARE @ing_pan_ex Ingredients_List; 
INSERT INTO @ing_pan_ex VALUES (3), (4); 
EXEC Add_Product 'Panadol Extra', 'BAR-002-E', 2, 2, 1, @ing_pan_ex;

DECLARE @ing_gal Ingredients_List; 
INSERT INTO @ing_gal VALUES (5), (6); 
EXEC Add_Product 'Galvus Met 50/1000', 'BAR-003', 3, 3, 3, @ing_gal;

DECLARE @ing_exf Ingredients_List; 
INSERT INTO @ing_exf VALUES (7), (8); 
EXEC Add_Product 'Exforge 5/160', 'BAR-004', 3, 4, 3, @ing_exf;

DECLARE @ing_ant Ingredients_List; 
INSERT INTO @ing_ant VALUES (1);
EXEC Add_Product 'Antinal Caps', 'BAR-005', 9, 5, 3, @ing_ant;

DECLARE @ing_con Ingredients_List;
INSERT INTO @ing_con VALUES (7);
EXEC Add_Product 'Concor 5 Plus', 'BAR-006', 8, 4, 1, @ing_con;

----------------

EXEC Add_supplier 'United Pharmacists', '010111222', 'TAX-V-99';
EXEC Add_supplier 'Ibn Sina Pharma', '012333444', 'TAX-V-101';
EXEC Add_supplier 'Overseas Distribution', '011555666', 'TAX-V-202';

DECLARE @order1 Order_Items_Table;
INSERT INTO @order1 VALUES 
(1, 100),	-- Augmentin
(2, 150),	-- Panadol Extra
(3, 80),	-- Galvus Met
(4, 60),	-- Exforge
(5, 200),	-- Antinal
(6, 40);	-- Concor
EXEC Add_Order 1, 1, '2026-01-28', @order1;

DECLARE @rec_data Received_Items_Table;
INSERT INTO @rec_data (product_id, quantity, batch_number, manufacture_date, expiry_date, cost_price, public_price)
VALUES 
(1, 100, 'B-AUG-244', '2025-12-01', '2028-12-01', 72.00, 98.00),
(2, 150, 'B-PAN-203', '2025-12-10', '2029-12-01', 16.00, 27.00),
(3, 80,  'B-GAL-102', '2025-11-01', '2027-11-01', 120.00, 165.00),
(4, 60,  'B-EXF-909', '2025-10-01', '2028-10-01', 180.00, 240.00),
(5, 200, 'B-ANT-505', '2026-01-01', '2029-01-01', 25.00, 40.00),
(6, 40,  'B-CON-303', '2025-09-01', '2028-09-01', 45.00, 65.00);

EXEC Receive_Order 1, 1, 12, 1, 30200.00, 0, 30200.00, 'Cash', 1, @rec_data;

----------------

DECLARE @sale1 Items_Table; 
INSERT INTO @sale1 VALUES (1, 3);
EXEC Add_Sale_Invoice 1, 2, 8, 0, 294.00, 'Cash', NULL, 'Walk-in', 'Customer', '000', @sale1;

DECLARE @sale2 Items_Table;
INSERT INTO @sale2 VALUES (3, 1);
EXEC Add_Sale_Invoice 1, 2, 10, 15.00, 100.00, 'Cash', NULL, 'Mohamed', 'Said', '0100', @sale2;

EXEC Add_Prescription 3, 'Dr. Ahmed Zewail', 'Mohamed Said', 'Take 1 tablet after breakfast';

DECLARE @ret1 Returned_Items_Table;
INSERT INTO @ret1 VALUES (10, 1);
EXEC Return_items 1, 11, 1, 2, 'Cash', @ret1;

EXEC Collect_Client_Due 2, 1, 2, 2, 50.00, 'Cash', 13;

----------------

EXEC Add_Internal_Transfer 1, 2, 2, 20, '2026-01-28', 9;


EXEC Receive_Internal_Transfer 1, 24;
